# Create a dictionary with ALL features from your training data
new_house = {
    # Categorical features (40 total)
    'MSZoning': 'RL',
    'Street': 'Pave',
    'Alley': None,
    'LotShape': 'Reg',
    'LandContour': 'Lvl',
    'Utilities': 'AllPub',
    'LotConfig': 'Inside',
    'LandSlope': 'Gtl',
    'Condition1': 'Norm',
    'Condition2': 'Norm',
    'BldgType': '1Fam',
    'HouseStyle': '2Story',
    'RoofStyle': 'Gable',
    'RoofMatl': 'CompShg',
    'MasVnrType': 'BrkFace',
    'ExterQual': 'Gd',
    'ExterCond': 'TA',
    'Foundation': 'PConc',
    'BsmtQual': 'Gd',
    'BsmtCond': 'TA',
    'BsmtExposure': 'No',
    'BsmtFinType1': 'GLQ',
    'BsmtFinType2': 'Unf',
    'Heating': 'GasA',
    'HeatingQC': 'Ex',
    'CentralAir': 'Y',
    'Electrical': 'SBrkr',
    'KitchenQual': 'Gd',
    'Functional': 'Typ',
    'FireplaceQu': None,
    'GarageType': 'Attchd',
    'GarageFinish': 'RFn',
    'GarageQual': 'TA',
    'GarageCond': 'TA',
    'PavedDrive': 'Y',
    'PoolQC': None,
    'Fence': None,
    'MiscFeature': None,
    'SaleType': 'WD',
    'SaleCondition': 'Normal',
    
    # Numerical features (36 total)
    'MSSubClass': 60,
    'LotFrontage': 65.0,
    'LotArea': 8450,
    'OverallQual': 7,
    'OverallCond': 5,
    'YearBuilt': 2003,
    'YearRemodAdd': 2003,
    'MasVnrArea': 196.0,
    'BsmtFinSF1': 706,
    'BsmtFinSF2': 0,
    'BsmtUnfSF': 150,
    'TotalBsmtSF': 856,
    '1stFlrSF': 856,
    '2ndFlrSF': 854,
    'LowQualFinSF': 0,
    'GrLivArea': 1710,
    'BsmtFullBath': 1,
    'BsmtHalfBath': 0,
    'FullBath': 2,
    'HalfBath': 1,
    'BedroomAbvGr': 3,
    'KitchenAbvGr': 1,
    'TotRmsAbvGrd': 8,
    'Fireplaces': 0,
    'GarageYrBlt': 2003.0,
    'GarageCars': 2,
    'GarageArea': 548,
    'WoodDeckSF': 0,
    'OpenPorchSF': 61,
    'EnclosedPorch': 0,
    '3SsnPorch': 0,
    'ScreenPorch': 0,
    'PoolArea': 0,
    'MiscVal': 0,
    'MoSold': 2,
    'YrSold': 2008
}

# Convert to DataFrame
new_house_df = pd.DataFrame([new_house])

# Predict
predicted_price = my_pipeline.predict(new_house_df)
print(f"Predicted Price: ${predicted_price[0]:,.2f}")
